--find the first and last names of players who were not born in the United States
SELECT COUNT("birth_country") FROM "players"
WHERE "birth_country" IS NOT 'USA';

sqlite> .read 4.sql
+------------------------+
| COUNT("birth_country") |
+------------------------+
| 2814                   |
+------------------------+
sqlite> .read 4.sql
+-------------+---------------+
| first_name  |   last_name   |
+-------------+---------------+
| NULL        | Spencer       |
| NULL        | O'Rourke      |
| NULL        | Higby         |
| NULL        | McDoolan      |
| NULL        | McGovern      |
| NULL        | Quinlan       |
| NULL        | Wood          |
| NULL        | Booth         |
| NULL        | Evans         |
| NULL        | Boland        |
| NULL        | Quinn         |
| NULL        | Edwards       |
| NULL        | Shaffer       |
| NULL        | Stoddard      |
| NULL        | Sheridan      |
| NULL        | Farrell       |
| NULL        | Carroll       |
| NULL        | Pierce        |
| NULL        | Wills         |
| NULL        | Smith         |
| NULL        | McRemer       |
| NULL        | Scott         |
| NULL        | Murphy        |
| NULL        | Franklin      |
| NULL        | Jones         |
| NULL        | McBride       |
| NULL        | Stafford      |
| NULL        | Sweigert      |
| NULL        | Leonard       |
| NULL        | Harrison      |
| NULL        | Hillebrand    |
| A. J.       | Jimenez       |
| Aaron       | Myette        |
| Aaron       | Guiel         |
| Aaron       | Altherr       |
| Aaron       | Whitefield    |
| Abbie       | Johnson       |
| Abel        | De Los Santos |
| Abiatal     | Avelino       |
| Abraham     | Nunez         |
| Abraham     | Nunez         |
| Abraham     | Almonte       |
| Abraham     | Toro          |
| Adalberto   | Mendez        |
| Adalberto   | Mejia         |
| Adam        | Stern         |
| Adam        | Loewen        |
| Adbert      | Alzolay       |
| Adeiny      | Hechavarria   |
| Adolfo      | Phillips      |
| Adolis      | Garcia        |
| Adonis      | Garcia        |
| Adonis      | Rosa          |
| Adonis      | Medina        |
| Adrian      | Zabala        |
| Adrian      | Beltre        |
| Adrian      | Hernandez     |
| Adrian      | Nieto         |
| Adrian      | Sanchez       |
| Adrian      | Morejon       |
| Adrian      | Martinez      |
| Agustin     | Montero       |
| Akeel       | Morris        |
| Akinori     | Otsuka        |
| Akinori     | Iwamura       |
| Al          | Reach         |
| Al          | Thake         |
| Al          | Nichols       |
| Al          | Skinner       |
| Al          | Lawson        |
| Al          | Shaw          |
| Al          | Campanis      |
| Al          | McBean        |
| Al          | Javier        |
| Al          | Pardo         |
| Al          | Pedrique      |
| Al          | Alburquerque  |
| Alay        | Soler         |
| Albert      | Williams      |
| Albert      | Pujols        |
| Albert      | Suarez        |
| Albert      | Abreu         |
| Alberto     | Lois          |
| Alberto     | Reyes         |
| Alberto     | Castillo      |
| Alberto     | Callaspo      |
| Alberto     | Arias         |
| Alberto     | Gonzalez      |
| Alberto     | Castillo      |
| Alberto     | Cabrera       |
| Alberto     | Rosario       |
| Alberto     | Baldonado     |
| Alcides     | Escobar       |
| Aldon       | Wilkie        |
| Aledmys     | Diaz          |
| Alejandro   | Pena          |
| Alejandro   | Sanchez       |
| Alejandro   | Freire        |
| Alejandro   | Machado       |
| Alejandro   | De Aza        |
| Alejandro   | Chacin        |
| Alejandro   | Kirk          |
| Alejo       | Lopez         |
| Alen        | Hanson        |
| Alex        | Gardner       |
| Alex        | Hardy         |
| Alex        | Carrasquel    |
| Alex        | Taveras       |
| Alex        | Trevino       |
| Alex        | Delgado       |
| Alex        | Pacheco       |
| Alex        | Cora          |
| Alex        | Gonzalez      |
| Alex        | Ramirez       |
| Alex        | Cabrera       |
| Alex        | Hernandez     |
| Alex        | Escobar       |
| Alex        | Sanchez       |
| Alex        | Cintron       |
| Alex        | Herrera       |
| Alex        | Prieto        |
| Alex        | Romero        |
| Alex        | Serrano       |
| Alex        | Torres        |
| Alex        | Liddi         |
| Alex        | Wilson        |
| Alex        | Colome        |
| Alex        | Guerrero      |
| Alex        | Claudio       |
| Alex        | Wells         |
| Alexei      | Ramirez       |
| Alexi       | Casilla       |
| Alexi       | Ogando        |
| Alexi       | Amarista      |
| Alexis      | Infante       |
| Alexis      | Gomez         |
| Alexis      | Diaz          |
| Alfonso     | Pulido        |
| Alfonso     | Soriano       |
| Alfredo     | Cabrera       |
| Alfredo     | Griffin       |
| Alfredo     | Amezaga       |
| Alfredo     | Aceves        |
| Alfredo     | Simon         |
| Alfredo     | Figaro        |
| Alfredo     | Marte         |
| Alfredo     | Gonzalez      |
| Ali         | Solis         |
| Ali         | Sanchez       |
| Allan       | Lewis         |
| Allen       | Cordoba       |
| Alvaro      | Espinoza      |
| Alvin       | Colina        |
| Amado       | Samuel        |
| Amalio      | Carreno       |
| Amauri      | Sanit         |
| Amaury      | Telemaco      |
| Amaury      | Garcia        |
| Ambiorix    | Burgos        |
| Amed        | Rosario       |
| Anastacio   | Martinez      |
| Anderson    | Machado       |
| Anderson    | Hernandez     |
| Anderson    | Garcia        |
| Anderson    | Tejeda        |
| Anderson    | Severino      |
| Anderson    | Espinoza      |
| Andre       | Rodgers       |
| Andre       | Rienzo        |
| Andrelton   | Simmons       |
| Andres      | Mora          |
| Andres      | Galarraga     |
| Andres      | Thomas        |
| Andres      | Santana       |
| Andres      | Berumen       |
| Andres      | Blanco        |
| Andres      | Machado       |
| Andres      | Munoz         |
| Andres      | Gimenez       |
| Andrew      | Albers        |
| Andruw      | Jones         |
| Andruw      | Monasterio    |
| Andujar     | Cedeno        |
| Andy        | Leonard       |
| Andy        | Cusick        |
| Andy        | Kyle          |
| Andy        | Mota          |
| Andy        | Stewart       |
| Andy        | Marte         |
| Andy        | Gonzalez      |
| Andy        | Ibanez        |
| Aneury      | Rodriguez     |
| Aneurys     | Zabala        |
| Angel       | Aragon        |
| Angel       | Fleitas       |
| Angel       | Bravo         |
| Angel       | Mangual       |
| Angel       | Torres        |
| Angel       | Moreno        |
| Angel       | Salazar       |
| Angel       | Escobar       |
| Angel       | Miranda       |
| Angel       | Pena          |
| Angel       | Santos        |
| Angel       | Berroa        |
| Angel       | Chavez        |
| Angel       | Pagan         |
| Angel       | Guzman        |
| Angel       | Sanchez       |
| Angel       | Salome        |
| Angel       | Nesbitt       |
| Angel       | Castro        |
| Angel       | Sanchez       |
| Angel       | Perdomo       |
| Angel       | Rondon        |
| Angel       | Zerpa         |
| Angel       | De Jesus      |
| Angelo      | Encarnacion   |
| Anibal      | Sanchez       |
| Anthony     | Ortega        |
| Anthony     | Santander     |
| Anthony     | Castro        |
| Antoan      | Richardson    |
| Antonio     | Osuna         |
| Antonio     | Alfonseca     |
| Antonio     | Perez         |
| Antonio     | Bastardo      |
| Antonio     | Senzatela     |
| Antonio     | Santos        |
| Aquilino    | Lopez         |
| Aramis      | Ramirez       |
| Arcenio     | Leon          |
| Argenis     | Reyes         |
| Argenis     | Diaz          |
| Ariel       | Prieto        |
| Ariel       | Pena          |
| Ariel       | Miranda       |
| Ariel       | Hernandez     |
| Ariel       | Jurado        |
| Arismendy   | Alcantara     |
| Aristides   | Aquino        |
| Armando     | Marsans       |
| Armando     | Roche         |
| Armando     | Reynoso       |
| Armando     | Benitez       |
| Armando     | Rios          |
| Armando     | Galarraga     |
| Armando     | Gabino        |
| Arndt       | Jorgens       |
| Arnie       | Munoz         |
| Arnold      | Leon          |
| Arodys      | Vizcaino      |
| Aroldis     | Chapman       |
| Arquimedes  | Caminero      |
| Arquimedez  | Pozo          |
| Art         | McGovern      |
| Art         | Lopez         |
| Arthur      | Irwin         |
| Arturo      | DeFreites     |
| Arturo      | Lopez         |
| Asdrubal    | Cabrera       |
| Atahualpa   | Severino      |
| Audry       | Perez         |
| Aurelio     | Monteagudo    |
| Aurelio     | Rodriguez     |
| Aurelio     | Lopez         |
| Austin      | Brice         |
| Avisail     | Garcia        |
| Axel        | Lindstrom     |
| Balvino     | Galvez        |
| Barbaro     | Garbey        |
| Barbaro     | Canizares     |
| Barney      | McLaughlin    |
| Barney      | Dreyfuss      |
| Barry       | Cort          |
| Bartolo     | Colon         |
| Bartolome   | Fortunato     |
| Beany       | Jacobson      |
| Beiker      | Graterol      |
| Beltran     | Perez         |
| Ben         | Laughlin      |
| Ben         | Koehler       |
| Ben         | Oglivie       |
| Ben         | Rivera        |
| Bengie      | Molina        |
| Benito      | Santiago      |
| Benito      | Baez          |
| Benji       | Gil           |
| Benny       | Valenzuela    |
| Benny       | Ayala         |
| Bernardo    | Brito         |
| Bernie      | Williams      |
| Bernie      | Castro        |
| Bert        | Sincock       |
| Bert        | Cueto         |
| Bert        | Campaneris    |
| Bert        | Blyleven      |
| Bert        | Pena          |
| Bien        | Figueroa      |
| Bill        | Sullivan      |
| Bill        | Phillips      |
| Bill        | Kuehne        |
| Bill        | Mountjoy      |
| Bill        | Hunter        |
| Bill        | Watkins       |
| Bill        | Collins       |
| Bill        | Farmer        |
| Bill        | Pfann         |
| Bill        | Magee         |
| Bill        | Cristall      |
| Bill        | Miller        |
| Bill        | O'Hara        |
| Bill        | Lelivelt      |
| Bill        | Jones         |
| Bill        | Zimmerman     |
| Bill        | Harris        |
| Bill        | Haywood       |
| Bill        | Castro        |
| Bill        | Atkinson      |
| Bill        | Ortega        |
| Billy       | Reid          |
| Blake       | Hawksworth    |
| Bo          | Diaz          |
| Bo          | Naylor        |
| Bob         | Addy          |
| Bob         | Valentine     |
| Bob         | Casey         |
| Bob         | Emslie        |
| Bob         | Troy          |
| Bob         | Steele        |
| Bob         | Hooper        |
| Bob         | Greenwood     |
| Bob         | Alexander     |
| Bob         | Davidson      |
| Bobby       | Clack         |
| Bobby       | Estalella     |
| Bobby       | Thomson       |
| Bobby       | Avila         |
| Bobby       | Herrera       |
| Bobby       | Prescott      |
| Bobby       | Trevino       |
| Bobby       | Fenwick       |
| Bobby       | Ramos         |
| Bobby       | Munoz         |
| Bobby       | Chouinard     |
| Bobby       | Abreu         |
| Bombo       | Rivera        |
| Brad        | Thomas        |
| Brad        | Harman        |
| Brailyn     | Marquez       |
| Braulio     | Castillo      |
| Brayan      | Pena          |
| Brayan      | Villarreal    |
| Brayan      | Bello         |
| Brayan      | Rocchio       |
| Brendan     | Donovan       |
| Brett       | Lawrie        |
| Breyvic     | Valera        |
| Brian       | Ostrosser     |
| Brian       | Lesher        |
| Brian       | Navarreto     |
| Bruce       | Bochy         |
| Bruce       | Chen          |
| Bruce       | Rondon        |
| Bruce       | Maxwell       |
| Brusdar     | Graterol      |
| Bryan       | Oelkers       |
| Bryan       | Abreu         |
| Bryan       | De La Cruz    |
| Bunk        | Congalton     |
| Byung Ho    | Park          |
| Byung-Hyun  | Kim           |
| C. C.       | Lee           |
| Cal         | Quantrill     |
| Callix      | Crabbe        |
| Calvin      | Maduro        |
| Calvin      | Pickering     |
| Cameron     | Cairncross    |
| Camilo      | Pascual       |
| Camilo      | Doval         |
| Candy       | Maldonado     |
| Candy       | Sierra        |
| Carl        | Linhart       |
| Carlos      | Pascual       |
| Carlos      | Bernier       |
| Carlos      | Paula         |
| Carlos      | Velazquez     |
| Carlos      | Lopez         |
| Carlos      | Lezcano       |
| Carlos      | Ponce         |
| Carlos      | Martinez      |
| Carlos      | Quintana      |
| Carlos      | Baerga        |
| Carlos      | Hernandez     |
| Carlos      | Maldonado     |
| Carlos      | Garcia        |
| Carlos      | Rodriguez     |
| Carlos      | Delgado       |
| Carlos      | Pulido        |
| Carlos      | Perez         |
| Carlos      | Valdez        |
| Carlos      | Mendoza       |
| Carlos      | Almanzar      |
| Carlos      | Guillen       |
| Carlos      | Beltran       |
| Carlos      | Febles        |
| Carlos      | Lee           |
| Carlos      | Hernandez     |
| Carlos      | Casimiro      |
| Carlos      | Hernandez     |
| Carlos      | Zambrano      |
| Carlos      | Pena          |
| Carlos      | Silva         |
| Carlos      | Mendez        |
| Carlos      | Valderrama    |
| Carlos      | Rivera        |
| Carlos      | Martinez      |
| Carlos      | Ruiz          |
| Carlos      | Villanueva    |
| Carlos      | Marmol        |
| Carlos      | Maldonado     |
| Carlos      | Gomez         |
| Carlos      | Gonzalez      |
| Carlos      | Rosa          |
| Carlos      | Corporan      |
| Carlos      | Carrasco      |
| Carlos      | Monasterios   |
| Carlos      | Santana       |
| Carlos      | Peguero       |
| Carlos      | Triunfel      |
| Carlos      | Martinez      |
| Carlos      | Contreras     |
| Carlos      | Frias         |
| Carlos      | Rivero        |
| Carlos      | Perez         |
| Carlos      | Correa        |
| Carlos      | Estevez       |
| Carlos      | Asuaje        |
| Carlos      | Ramirez       |
| Carlos      | Tocci         |
| Carlos      | Sanabria      |
| Carlos      | Hernandez     |
| Carlos      | Perez         |
| Carlos      | Vargas        |
| Carlos      | Tosca         |
| Carmelo     | Castillo      |
| Carmelo     | Martinez      |
| Cecilio     | Guante        |
| Celerino    | Sanchez       |
| Cesar       | Tovar         |
| Cesar       | Gutierrez     |
| Cesar       | Geronimo      |
| Cesar       | Cedeno        |
| Cesar       | Hernandez     |
| Cesar       | Devarez       |
| Cesar       | Crespo        |
| Cesar       | Izturis       |
| Cesar       | Jimenez       |
| Cesar       | Valdez        |
| Cesar       | Hernandez     |
| Cesar       | Cabral        |
| Cesar       | Vargas        |
| Cesar       | Puello        |
| Cesar       | Salazar       |
| Cha-Seung   | Baek          |
| Chadwick    | Tromp         |
| Chan Ho     | Park          |
| Chang-Yong  | Lim           |
| Charles     | Leblanc       |
| Charlie     | Ritter        |
| Charlie     | Hallstrom     |
| Charlie     | McCullough    |
| Charlie     | Hanford       |
| Charlie     | Bold          |
| Charlie     | Mead          |
| Charlie     | Lea           |
| Charlie     | Montoyo       |
| Che-Hsuan   | Lin           |
| Cheslor     | Cuthbert      |
| Chi-Chi     | Olivo         |
| Chia-Jen    | Lo            |
| Chick       | Pedroes       |
| Chico       | Hernandez     |
| Chico       | Carrasquel    |
| Chico       | Garcia        |
| Chico       | Fernandez     |
| Chico       | Ruiz          |
| Chico       | Salmon        |
| Chico       | Ruiz          |
| Chico       | Escarrega     |
| Chien-Ming  | Wang          |
| Chih-Wei    | Hu            |
| Chile       | Gomez         |
| Chili       | Davis         |
| Chin-Feng   | Chen          |
| Chin-hui    | Tsao          |
| Chin-lung   | Hu            |
| Chino       | Cadahia       |
| Chito       | Martinez      |
| Cholly      | Naranjo       |
| Chris       | Mears         |
| Chris       | Oxspring      |
| Chris       | Leroux        |
| Chris       | Robinson      |
| Chris       | Reed          |
| Chris       | Von Der Ahe   |
| Christian   | Bethancourt   |
| Christian   | Colon         |
| Christian   | Vazquez       |
| Christian   | Villanueva    |
| Christopher | Morel         |
| Chub        | Collins       |
| Chucho      | Ramos         |
| Cionel      | Perez         |
| Clarence    | Murphy        |
| Clarence    | Currie        |
| Claude      | Gouzzie       |
| Claude      | Raymond       |
| Claudio     | Vargas        |
| Clemente    | Alvarez       |
| Coco        | Laboy         |
| Cody        | McKay         |
| Con         | Lucid         |
| Con         | Starkel       |
| Connie      | Marrero       |
| Conny       | Doyle         |
| Cookie      | Rojas         |
| Cooney      | Snyder        |
| Corey       | Koskie        |
| Craig       | Lefferts      |
| Craig       | Shipley       |
| Craig       | House         |
| Craig       | Stansberry    |
| Cris        | Colon         |
| Cristhian   | Martinez      |
| Cristhian   | Adames        |
| Cristian    | Guzman        |
| Cristian    | Javier        |
| Cristian    | Pache         |
| Cristobal   | Torriente     |
| Cristofer   | Ogando        |
| Cristopher  | Sanchez       |
| Curry       | Foley         |
| Cy          | Acosta        |
| Cyclone     | Ryan          |
| D'Angelo    | Jimenez       |
| Dae-Sung    | Koo           |
| Dae-ho      | Lee           |
| Dairon      | Blanco        |
| Daisuke     | Matsuzaka     |
| Dalier      | Hinojosa      |
| Dalton      | Pompey        |
| Damaso      | Blanco        |
| Damaso      | Garcia        |
| Damaso      | Marte         |
| Damian      | Moss          |
| Damon       | Mashore       |
| Dan         | O'Connor      |
| Daniel      | Garibay       |
| Daniel      | Cabrera       |
| Daniel      | Corcino       |
| Daniel      | Castro        |
| Daniel      | Duarte        |
| Danny       | Morejon       |
| Danny       | Cox           |
| Danny       | Tartabull     |
| Danny       | Leon          |
| Danny       | Bautista      |
| Danny       | Graves        |
| Danny       | Rios          |
| Danny       | Klassen       |
| Danny       | Mota          |
| Danny       | Sandoval      |
| Danny       | Richar        |
| Danny       | Salazar       |
| Danny       | Santana       |
| Danny       | Ortiz         |
| Dany        | Jimenez       |
| Danys       | Baez          |
| Dariel      | Alvarez       |
| Darien      | Nunez         |
| Dario       | Veras         |
| Dario       | Alvarez       |
| Dario       | Agrazal       |
| Darwin      | Cubillan      |
| Darwinzon   | Hernandez     |
| Dauri       | Moreta        |
| Dave        | Drew          |
| Dave        | Brain         |
| Dave        | Rowan         |
| Dave        | Roberts       |
| Dave        | Concepcion    |
| Dave        | Rosello       |
| Dave        | Pagan         |
| Dave        | McKay         |
| Dave        | Shipanoff     |
| Dave        | Pavlas        |
| Dave        | Wainhouse     |
| Dave        | Nilsson       |
| Dave        | Roberts       |
| Dave        | Davidson      |
| David       | Lenz          |
| David       | Green         |
| David       | Ortiz         |
| David       | Cortes        |
| David       | Martinez      |
| David       | Peralta       |
| David       | Paulino       |
| Davis       | Romero        |
| Dawel       | Lugo          |
| Dayan       | Viciedo       |
| Dayan       | Diaz          |
| Deivi       | Cruz          |
| Deivi       | Garcia        |
| Deivy       | Grullon       |
| Denis       | Boucher       |
| Denis       | Phipps        |
| Dennis      | Fitzgerald    |
| Dennis      | Martinez      |
| Dennis      | Santana       |
| Denny       | Gonzalez      |
| Denny       | Bautista      |
| Dennys      | Reyes         |
| Denyi       | Reyes         |
| Deolis      | Guerra        |
| Derek       | Aucoin        |
| Dermis      | Garcia        |
| Devern      | Hansack       |
| Devon       | White         |
| Dick        | Higham        |
| Dick        | Fowler        |
| Dick        | Lines         |
| Dicky       | Gonzalez      |
| Didi        | Gregorius     |
| Diego       | Segui         |
| Diego       | Moreno        |
| Diego       | Castillo      |
| Diego       | Castillo      |
| Dilson      | Torres        |
| Dilson      | Herrera       |
| Dinelson    | Lamet         |
| Diomedes    | Olivo         |
| Dioner      | Navarro       |
| Diory       | Hernandez     |
| Dixon       | Machado       |
| Doc         | Miller        |
| Dolf        | Luque         |
| Domingo     | Ramos         |
| Domingo     | Martinez      |
| Domingo     | Cedeno        |
| Domingo     | Jean          |
| Domingo     | Guzman        |
| Domingo     | Santana       |
| Domingo     | German        |
| Domingo     | Leyba         |
| Domingo     | Tapia         |
| Domingo     | Acevedo       |
| Donaldo     | Mendez        |
| Donovan     | Solano        |
| Doug        | Frobel        |
| Dovydas     | Neverauskas   |
| Duaner      | Sanchez       |
| Duke        | Markell       |
| Dustin      | Molleken      |
| Dutch       | Schliebner    |
| Dutch       | Schesler      |
| Earl        | Cook          |
| Ed          | Duffy         |
| Ed          | Cogswell      |
| Ed          | Smith         |
| Ed          | Springer      |
| Ed          | Eiteljorge    |
| Ed          | Walker        |
| Ed          | Pinnance      |
| Ed          | Kippert       |
| Ed          | Porray        |
| Ed          | Wingo         |
| Ed          | Bahr          |
| Ed          | Bauta         |
| Ed          | Acosta        |
| Ed          | Armbrister    |
| Ed          | Figueroa      |
| Ed          | Romero        |
| Ed          | Nunez         |
| Ed          | Correa        |
| Eddie       | Ainsmith      |
| Eddie       | Vargas        |
| Eddie       | Zambrano      |
| Eddie       | Perez         |
| Eddie       | Oropesa       |
| Eddie       | Rogers        |
| Eddie       | Rosario       |
| Eddy        | Diaz          |
| Eddy        | Rodriguez     |
| Eddy        | Garabito      |
| Eddy        | Rodriguez     |
| Edgar       | Diaz          |
| Edgar       | Caceres       |
| Edgar       | Renteria      |
| Edgar       | Ramos         |
| Edgar       | Gonzalez      |
| Edgar       | Ibarra        |
| Edgar       | Santana       |
| Edgar       | Garcia        |
| Edgard      | Clemente      |
| Edgardo     | Alfonzo       |
| Edgmer      | Escalona      |
| Edinson     | Volquez       |
| Edmundo     | Sosa          |
| Edouard     | Julien        |
| Eduard      | Bazardo       |
| Eduardo     | Rodriguez     |
| Eduardo     | Villacis      |
| Eduardo     | Nunez         |
| Eduardo     | Sanchez       |
| Eduardo     | Escobar       |
| Eduardo     | Rodriguez     |
| Eduardo     | Paredes       |
| Eduardo     | Jimenez       |
| Eduardo     | Salazar       |
| Edubray     | Ramos         |
| Edwar       | Ramirez       |
| Edwar       | Cabrera       |
| Edwar       | Colina        |
| Edward      | Mujica        |
| Edward      | Paredes       |
| Edward      | Olivares      |
| Edward      | Cabrera       |
| Edwards     | Guzman        |
| Edwin       | Rodriguez     |
| Edwin       | Hurtado       |
| Edwin       | Diaz          |
| Edwin       | Almonte       |
| Edwin       | Jackson       |
| Edwin       | Encarnacion   |
| Edwin       | Bellorin      |
| Edwin       | Maysonet      |
| Edwin       | Moreno        |
| Edwin       | Escobar       |
| Edwin       | Diaz          |
| Edwin       | Rios          |
| Edwin       | Uceta         |
| Efrain      | Valdez        |
| Eguy        | Rosario       |
| Ehire       | Adrianza      |
| Eider       | Torres        |
| Einar       | Diaz          |
| Elehuris    | Montero       |
| Eli         | Marrero       |
| Elian       | Herrera       |
| Elias       | Sosa          |
| Elias       | Diaz          |
| Elier       | Hernandez     |
| Elieser     | Hernandez     |
| Eliezer     | Alfonzo       |
| Elio        | Chacon        |
| Elizardo    | Ramirez       |
| Ellie       | Rodriguez     |
| Elmer       | Valo          |
| Elmer       | Dessens       |
| Elmo        | Plaskett      |
| Eloy        | Jimenez       |
| Elrod       | Hendricks     |
| Elvin       | Ramirez       |
| Elvin       | Rodriguez     |
| Elvio       | Jimenez       |
| Elvis       | Pena          |
| Elvis       | Andrus        |
| Elvis       | Araujo        |
| Elvis       | Luciano       |
| Elvis       | Peguero       |
| Emiliano    | Fruto         |
| Emilio      | Palmero       |
| Emilio      | Bonifacio     |
| Emmanuel    | Clase         |
| Emmanuel    | Rivera        |
| Ender       | Inciarte      |
| Enderson    | Franco        |
| Endy        | Chavez        |
| Enerio      | Del Rosario   |
| Engel       | Beltre        |
| Engelb      | Vielma        |
| Enmanuel    | Valdez        |
| Enny        | Romero        |
| Enoli       | Paredes       |
| Enrique     | Romo          |
| Enrique     | Burgos        |
| Enrique     | Wilson        |
| Enrique     | Cruz          |
| Enrique     | Gonzalez      |
| Enrique     | Hernandez     |
| Enrique     | Burgos        |
| Enyel       | De Los Santos |
| Enzo        | Hernandez     |
| Erasmo      | Ramirez       |
| Eric        | Erickson      |
| Eric        | MacKenzie     |
| Eric        | Gagne         |
| Eric        | Cyr           |
| Erick       | Almonte       |
| Erick       | Aybar         |
| Erick       | Mejia         |
| Erick       | Castillo      |
| Erik        | Bedard        |
| Erik        | Gonzalez      |
| Erisbel     | Arruebarrena  |
| Ernesto     | Frieri        |
| Ernie       | Ross          |
| Erubiel     | Durazo        |
| Ervin       | Santana       |
| Esmailin    | Caridad       |
| Esmerling   | Vasquez       |
| Esmil       | Rogers        |
| Esteban     | Beltre        |
| Esteban     | Loaiza        |
| Esteban     | Yan           |
| Esteban     | German        |
| Esteban     | Quiroz        |
| Esteury     | Ruiz          |
| Estevan     | Florial       |
| Eude        | Brito         |
| Eugenio     | Velez         |
| Eugenio     | Suarez        |
| Eury        | Perez         |
| Eury        | De La Rosa    |
| Eury        | Perez         |
| Eusebio     | Gonzalez      |
| Evelio      | Hernandez     |
| Ever        | Magallanes    |
| Everth      | Cabrera       |
| Ezequiel    | Astacio       |
| Ezequiel    | Carrera       |
| Ezequiel    | Duran         |
| Ezequiel    | Tovar         |
| Fabio       | Castro        |
| Fabio       | Castillo      |
| Fausto      | Cruz          |
| Fautino     | De Los Santos |
| Felipe      | Montemayor    |
| Felipe      | Alou          |
| Felipe      | Lira          |
| Felipe      | Crespo        |
| Felipe      | Lopez         |
| Felipe      | Paulino       |
| Felipe      | Vazquez       |
| Felix       | Mantilla      |
| Felix       | Torres        |
| Felix       | Millan        |
| Felix       | Fermin        |
| Felix       | Jose          |
| Felix       | Rodriguez     |
| Felix       | Heredia       |
| Felix       | Martinez      |
| Felix       | Escalona      |
| Felix       | Sanchez       |
| Felix       | Diaz          |
| Felix       | Hernandez     |
| Felix       | Pie           |
| Felix       | Doubront      |
| Felix       | Pena          |
| Felix       | Jorge         |
| Felix       | Bautista      |
| Fergie      | Jenkins       |
| Fergy       | Malone        |
| Fernando    | Gonzalez      |
| Fernando    | Valenzuela    |
| Fernando    | Ramsey        |
| Fernando    | Hernandez     |
| Fernando    | Tatis         |
| Fernando    | Seguignol     |
| Fernando    | Lunar         |
| Fernando    | Rodney        |
| Fernando    | Cabrera       |
| Fernando    | Nieve         |
| Fernando    | Martinez      |
| Fernando    | Salas         |
| Fernando    | Abad          |
| Fernando    | Romero        |
| Fernando    | Tatis         |
| Fernando    | Cruz          |
| Framber     | Valdez        |
| Franchy     | Cordero       |
| Francis     | Beltran       |
| Francis     | Martes        |
| Francisco   | Barrios       |
| Francisco   | Melendez      |
| Francisco   | Oliveras      |
| Francisco   | Cabrera       |
| Francisco   | de la Rosa    |
| Francisco   | Matos         |
| Francisco   | Cordova       |
| Francisco   | Cordero       |
| Francisco   | Rodriguez     |
| Francisco   | Santos        |
| Francisco   | Cruceta       |
| Francisco   | Liriano       |
| Francisco   | Rosario       |
| Francisco   | Cervelli      |
| Francisco   | Rodriguez     |
| Francisco   | Peguero       |
| Francisco   | Pena          |
| Francisco   | Lindor        |
| Francisco   | Mejia         |
| Francisco   | Arcia         |
| Francisco   | Perez         |
| Francisco   | Morales       |
| Francisco   | Alvarez       |
| Francisley  | Bueno         |
| Frank       | Thompson      |
| Frank       | McLaughlin    |
| Frank       | Smith         |
| Frank       | Meek          |
| Frank       | O'Rourke      |
| Frank       | Rooney        |
| Frank       | Ulrich        |
| Frank       | Colman        |
| Frank       | Campos        |
| Frank       | Estrada       |
| Frank       | Taveras       |
| Frank       | Gracesqui     |
| Frank       | Francisco     |
| Frank       | Mata          |
| Frank       | Garces        |
| Frank       | McKenna       |
| Frankie     | Libran        |
| Frankie     | De La Cruz    |
| Frankie     | Montas        |
| Franklin    | Nunez         |
| Franklin    | Gutierrez     |
| Franklin    | Morales       |
| Franklin    | Barreto       |
| Franklyn    | German        |
| Franklyn    | Kilome        |
| Franmil     | Reyes         |
| Franquelis  | Osoria        |
| Fred        | Wood          |
| Fred        | O'Neill       |
| Fred        | Osborne       |
| Fred        | Demarais      |
| Fred        | Lake          |
| Fred        | Gaiser        |
| Fred        | Manrique      |
| Freddie     | Velazquez     |
| Freddy      | Rodriguez     |
| Freddy      | Garcia        |
| Freddy      | Garcia        |
| Freddy      | Guzman        |
| Freddy      | Dolsi         |
| Freddy      | Sandoval      |
| Freddy      | Galvis        |
| Freddy      | Peralta       |
| Freddy      | Fermin        |
| Fredi       | Gonzalez      |
| Fritz       | Buelow        |
| Fritz       | Mollwitz      |
| Fu-Te       | Ni            |
| Gabe        | Alvarez       |
| Gabriel     | Ynoa          |
| Gabriel     | Moya          |
| Gabriel     | Guerrero      |
| Gabriel     | Arias         |
| Gabriel     | Moreno        |
| Gary        | Sanchez       |
| Gene        | Vadeboncoeur  |
| Gene        | Ford          |
| Gene        | Kingsale      |
| Genesis     | Cabrera       |
| George      | Hall          |
| George      | Heubel        |
| George      | Wood          |
| George      | Patterson     |
| George      | Walker        |
| George      | McMillan      |
| George      | Crawford      |
| George      | Gibson        |
| George      | Chalmers      |
| George      | Selkirk       |
| George      | Korince       |
| George      | Lauzerique    |
| George      | Bell          |
| George      | Kottaras      |
| George      | Soriano       |
| George      | Frazer        |
| George      | McManus       |
| Georges     | Maranda       |
| Geovany     | Soto          |
| Gerald      | Young         |
| Geraldo     | Guzman        |
| Geraldo     | Perdomo       |
| Gerardo     | Parra         |
| Gerardo     | Concepcion    |
| Gerardo     | Reyes         |
| Geremi      | Gonzalez      |
| German      | Barranca      |
| German      | Rivera        |
| German      | Jimenez       |
| German      | Gonzalez      |
| German      | Duran         |
| German      | Marquez       |
| Geronimo    | Berroa        |
| Geronimo    | Pena          |
| Geronimo    | Gil           |
| Gerson      | Bautista      |
| Gibson      | Alba          |
| Gift        | Ngoepe        |
| Gil         | Torres        |
| Gil         | Garrido       |
| Gil         | Flores        |
| Gil         | Reyes         |
| Gilberto    | Celestino     |
| Gio         | Urshela       |
| Giomar      | Guevara       |
| Giovanni    | Carrara       |
| Giovanni    | Soto          |
| Giovanny    | Gallegos      |
| Glen        | Gorbous       |
| Glenn       | Hubbard       |
| Glenn       | Williams      |
| Gleyber     | Torres        |
| Gonzalez    | Germen        |
| Gonzalo     | Marquez       |
| Goody       | Rosen         |
| Gordie      | Pladson       |
| Gorkys      | Hernandez     |
| Graeme      | Lloyd         |
| Grant       | Balfour       |
| Greg        | O'Halloran    |
| Greg        | Aquino        |
| Greg        | Infante       |
| Greg        | Halman        |
| Gregor      | Blanco        |
| Gregorio    | Petit         |
| Gregory     | Polanco       |
| Gregory     | Soto          |
| Gregory     | Santos        |
| Guilder     | Rodriguez     |
| Guillermo   | Velasquez     |
| Guillermo   | Garcia        |
| Guillermo   | Mota          |
| Guillermo   | Quiroz        |
| Guillermo   | Rodriguez     |
| Guillermo   | Moscoso       |
| Guillermo   | Heredia       |
| Guillermo   | Zuniga        |
| Gus         | Shallix       |
| Gus         | Yost          |
| Gus         | Dugas         |
| Gus         | Gil           |
| Gus         | Polidor       |
| Gustavo     | Chacin        |
| Gustavo     | Molina        |
| Ha-Seong    | Kim           |
| Hank        | Biasatti      |
| Hank        | Izquierdo     |
| Hanley      | Frias         |
| Hanley      | Ramirez       |
| Hansel      | Izquierdo     |
| Hansel      | Robles        |
| Hanser      | Alberto       |
| Harold      | Castro        |
| Harold      | Ramirez       |
| Harry       | Wright        |
| Harry       | Smith         |
| Harry       | Kingman       |
| Harry       | O'Neill       |
| Harry       | Sketchley     |
| Harry       | Fisher        |
| Harvey      | Shank         |
| Harvey      | Garcia        |
| Hector      | Rodriguez     |
| Hector      | Lopez         |
| Hector      | Maestri       |
| Hector      | Martinez      |
| Hector      | Valle         |
| Hector      | Torres        |
| Hector      | Cruz          |
| Hector      | Villanueva    |
| Hector      | Wagner        |
| Hector      | Fajardo       |
| Hector      | Carrasco      |
| Hector      | Ortiz         |
| Hector      | Almonte       |
| Hector      | Ramirez       |
| Hector      | Mercado       |
| Hector      | Luna          |
| Hector      | Gimenez       |
| Hector      | Noesi         |
| Hector      | Sanchez       |
| Hector      | Gomez         |
| Hector      | Rondon        |
| Hector      | Neris         |
| Hector      | Olivera       |
| Hector      | Velazquez     |
| Hector      | Perez         |
| Hee-Seop    | Choi          |
| Heinz       | Becker        |
| Heliot      | Ramos         |
| Henderson   | Alvarez       |
| Henry       | Mullin        |
| Henry       | Oxley         |
| Henry       | Youngman      |
| Henry       | Peploski      |
| Henry       | Cruz          |
| Henry       | Mercedes      |
| Henry       | Rodriguez     |
| Henry       | Blanco        |
| Henry       | Mateo         |
| Henry       | Rodriguez     |
| Henry       | Villar        |
| Henry       | Sosa          |
| Henry       | Rodriguez     |
| Henry       | Urrutia       |
| Henry       | Ramos         |
| Henry       | Chadwick      |
| Hensley     | Meulens       |
| Herb        | Worth         |
| Hernan      | Iribarren     |
| Hernan      | Perez         |
| Hideki      | Irabu         |
| Hideki      | Matsui        |
| Hideki      | Okajima       |
| Hideo       | Nomo          |
| Hipolito    | Pena          |
| Hipolito    | Pichardo      |
| Hiram       | Bithorn       |
| Hiram       | Bocachica     |
| Hiram       | Burgos        |
| Hirokazu    | Sawamura      |
| Hiroki      | Kuroda        |
| Hisanori    | Takahashi     |
| Hisashi     | Iwakuma       |
| Hobe        | Ferris        |
| Horace      | Clarke        |
| Horacio     | Pina          |
| Horacio     | Estrada       |
| Houston     | Jimenez       |
| Hoy         | Park          |
| Huascar     | Ynoa          |
| Huascar     | Brazoban      |
| Hugh        | Campbell      |
| Hugh        | Nicol         |
| Hugh        | Daily         |
| Hugh        | Gilgan        |
| Hugo        | Bezdek        |
| Humberto    | Robinson      |
| Humberto    | Cota          |
| Humberto    | Quintero      |
| Humberto    | Sanchez       |
| Humberto    | Arteaga       |
| Humberto    | Castellanos   |
| Humberto    | Mejia         |
| Hung-Chih   | Kuo           |
| Hyeon-jong  | Yang          |
| Hyun Jin    | Ryu           |
| Hyun Soo    | Kim           |
| Ichiro      | Suzuki        |
| Ildemaro    | Vargas        |
| Irish       | McIlveen      |
| Irving      | Falu          |
| Isaac       | Paredes       |
| Isan        | Diaz          |
| Isidro      | Marquez       |
| Ismael      | Valdez        |
| Ismael      | Villegas      |
| Israel      | Sanchez       |
| Israel      | Alcantara     |
| Israel      | Pineda        |
| Ivan        | Murrell       |
| Ivan        | de Jesus      |
| Ivan        | Calderon      |
| Ivan        | Rodriguez     |
| Ivan        | Cruz          |
| Ivan        | Ochoa         |
| Ivan        | Nova          |
| Ivan        | De Jesus      |
| Ivan        | Castillo      |
| Ivan        | Herrera       |
| Ivanon      | Coffie        |
| Izzy        | Goldstein     |
| Izzy        | Leon          |
| J. C.       | Romero        |
| J. C.       | Gutierrez     |
| J. C.       | Boscan        |
| J. C.       | Ramirez       |
| J. C.       | Mejia         |
| Jabari      | Blash         |
| Jack        | Doyle         |
| Jack        | Katoll        |
| Jack        | O'Neill       |
| Jack        | Burns         |
| Jack        | Cameron       |
| Jack        | Graney        |
| Jack        | Quinn         |
| Jack        | Lelivelt      |
| Jack        | Calvo         |
| Jack        | Aragon        |
| Jack        | Lopez         |
| Jackie      | Hernandez     |
| Jackie      | Gutierrez     |
| Jacob       | Robson        |
| Jae Kuk     | Ryu           |
| Jae Weong   | Seo           |
| Jae-gyun    | Hwang         |
| Jailen      | Peguero       |
| Jaime       | Cocanower     |
| Jaime       | Navarro       |
| Jaime       | Garcia        |
| Jaime       | Barria        |
| Jair        | Jurrjens      |
| Jairo       | Asencio       |
| Jairo       | Diaz          |
| Jairo       | Labourt       |
| Jake        | Gettman       |
| Jake        | Livingstone   |
| James       | Cavanagh      |
| James       | Haley         |
| James       | Pirie         |
| James       | Harris        |
| James       | Paxton        |
| James       | Beresford     |
| Jamie       | Romak         |
| Jandel      | Gustave       |
| Jared       | Young         |
| Jarlin      | Garcia        |
| Jason       | Dickson       |
| Jason       | Green         |
| Jason       | Bay           |
| Javier      | Valentin      |
| Javier      | Martinez      |
| Javier      | Vazquez       |
| Javier      | Cardona       |
| Javier      | Lopez         |
| Javier      | Baez          |
| Javier      | Assad         |
| Javy        | Lopez         |
| Javy        | Guerra        |
| Jay         | Clarke        |
| Jayson      | Aquino        |
| Jazz        | Chisholm      |
| Jean        | Segura        |
| Jean        | Machi         |
| Jean-Pierre | Roy           |
| Jeanmar     | Gomez         |
| Jeff        | Heath         |
| Jeff        | Bronkey       |
| Jeff        | McCurry       |
| Jeff        | Zimmerman     |
| Jeff        | Williams      |
| Jeff        | Francis       |
| Jeff        | Baker         |
| Jefry       | Marte         |
| Jefry       | Rodriguez     |
| Jen-Ho      | Tseng         |
| Jenrry      | Mejia         |
| Jerar       | Encarnacion   |
| Jeremy      | Pena          |
| Jermaine    | Palacios      |
| Jerry       | Moore         |
| Jerry       | Morales       |
| Jerry       | Browne        |
| Jerry       | Gil           |
| Jesen       | Therrien      |
| Jesmuel     | Valentin      |
| Jesse       | Flores        |
| Jesse       | Crain         |
| Jesus       | Alou          |
| Jesus       | Hernaiz       |
| Jesus       | de la Rosa    |
| Jesus       | Vega          |
| Jesus       | Figueroa      |
| Jesus       | Tavarez       |
| Jesus       | Sanchez       |
| Jesus       | Pena          |
| Jesus       | Colome        |
| Jesus       | Flores        |
| Jesus       | Delgado       |
| Jesus       | Guzman        |
| Jesus       | Feliciano     |
| Jesus       | Montero       |
| Jesus       | Sucre         |
| Jesus       | Aguilar       |
| Jesus       | Reyes         |
| Jesus       | Tinoco        |
| Jesus       | Luzardo       |
| Jesus       | Cruz          |
| Jesus       | Sanchez       |
| Jeter       | Downs         |
| Jeurys      | Familia       |
| Jhan        | Marinez       |
| Jharel      | Cotton        |
| Jhoan       | Duran         |
| Jhon        | Romero        |
| Jhonatan    | Solano        |
| Jhonathan   | Diaz          |
| Jhonny      | Peralta       |
| Jhonny      | Nunez         |
| Jhony       | Brito         |
| Jhoulys     | Chacin        |
| Ji Hwan     | Bae           |
| Ji Man      | Choi          |
| Jim         | Britt         |
| Jim         | Hall          |
| Jim         | McCormick     |
| Jim         | Halpin        |
| Jim         | McKeever      |
| Jim         | Cockman       |
| Jim         | Riley         |
| Jim         | Wright        |
| Jim         | Lawrence      |
| Jim         | Bowie         |
| Jim         | Henderson     |
| Jim         | Adduci        |
| Jimmy       | Hallinan      |
| Jimmy       | Knowles       |
| Jimmy       | Wiggs         |
| Jimmy       | Archer        |
| Jimmy       | Austin        |
| Jimmy       | Walsh         |
| Jimmy       | Rosario       |
| Jimmy       | Paredes       |
| Jimmy       | Cordero       |
| Jin Ho      | Cho           |
| Joakim      | Soria         |
| Joan        | Adon          |
| Joaquin     | Andujar       |
| Joaquin     | Benoit        |
| Joaquin     | Arias         |
| Jocko       | Fields        |
| Joe         | Miller        |
| Joe         | Quinn         |
| Joe         | Knight        |
| Joe         | Weber         |
| Joe         | Brown         |
| Joe         | Hovlik        |
| Joe         | Zapustas      |
| Joe         | Krakauskas    |
| Joe         | Cleary        |
| Joe         | Erautt        |
| Joe         | Christopher   |
| Joe         | Azcue         |
| Joe         | Siddall       |
| Joe         | Ortiz         |
| Joe         | Colon         |
| Joe         | Jimenez       |
| Joel        | Pineiro       |
| Joel        | Peralta       |
| Joel        | Guzman        |
| Joel        | Carreno       |
| Joel        | De La Cruz    |
| Joel        | Payamps       |
| Joely       | Rodriguez     |
| Joey        | Cora          |
| Joey        | Votto         |
| Joey        | Meneses       |
| Johan       | Santana       |
| Johan       | Camargo       |
| Johan       | Oviedo        |
| Johan       | Quezada       |
| John        | McGuinness    |
| John        | Curran        |
| John        | Magner        |
| John        | Stedronsky    |
| John        | Irwin         |
| John        | Doyle         |
| John        | Humphries     |
| John        | Tener         |
| John        | O'Brien       |
| John        | O'Connell     |
| John        | Anderson      |
| John        | Houseman      |
| John        | O'Neill       |
| John        | Michaelson    |
| John        | Kloza         |
| John        | Hiller        |
| John        | Upham         |
| John        | Balaz         |
| John        | Stephens      |
| John        | Hattig        |
| John        | Axford        |
| Johneshwy   | Fargas        |
| Johnny      | O'Connor      |
| Johnny      | Reder         |
| Johnny      | Rutherford    |
| Johnny      | Paredes       |
| Johnny      | Guzman        |
| Johnny      | Cueto         |
| Jolbert     | Cabrera       |
| Jon         | Morrison      |
| Jonathan    | Sanchez       |
| Jonathan    | Albaladejo    |
| Jonathan    | Herrera       |
| Jonathan    | Villar        |
| Jonathan    | Schoop        |
| Jonathan    | Aro           |
| Jonathan    | Loaisiga      |
| Jonathan    | Arauz         |
| Jonathan    | Aranda        |
| Jordan      | Zimmerman     |
| Jordan      | Norberto      |
| Jordan      | Romano        |
| Jordan      | Diaz          |
| Jordany     | Valdespin     |
| Jorge       | Comellas      |
| Jorge       | Rubio         |
| Jorge       | Roque         |
| Jorge       | Orta          |
| Jorge       | Brito         |
| Jorge       | Posada        |
| Jorge       | Velandia      |
| Jorge       | Toca          |
| Jorge       | Julio         |
| Jorge       | Sosa          |
| Jorge       | De Paula      |
| Jorge       | Vasquez       |
| Jorge       | De La Rosa    |
| Jorge       | Campillo      |
| Jorge       | Padilla       |
| Jorge       | De Leon       |
| Jorge       | Polanco       |
| Jorge       | Rondon        |
| Jorge       | Soler         |
| Jorge       | Lopez         |
| Jorge       | Alfaro        |
| Jorge       | Bonifacio     |
| Jorge       | Alcala        |
| Jorge       | Guzman        |
| Jorge       | Mateo         |
| Jorge       | Ona           |
| Jose        | Rodriguez     |
| Jose        | Acosta        |
| Jose        | Zardon        |
| Jose        | Santiago      |
| Jose        | Valdivielso   |
| Jose        | Pagan         |
| Jose        | Tartabull     |
| Jose        | Cardenal      |
| Jose        | Santiago      |
| Jose        | Vidal         |
| Jose        | Herrera       |
| Jose        | Arcia         |
| Jose        | Martinez      |
| Jose        | Pena          |
| Jose        | Ortiz         |
| Jose        | Cruz          |
| Jose        | Morales       |
| Jose        | Sosa          |
| Jose        | Baez          |
| Jose        | Moreno        |
| Jose        | Oquendo       |
| Jose        | DeLeon        |
| Jose        | Rijo          |
| Jose        | Roman         |
| Jose        | Uribe         |
| Jose        | Canseco       |
| Jose        | Gonzalez      |
| Jose        | Guzman        |
| Jose        | Nunez         |
| Jose        | Lind          |
| Jose        | Mesa          |
| Jose        | Cecena        |
| Jose        | Bautista      |
| Jose        | Segura        |
| Jose        | Cano          |
| Jose        | Vizcaino      |
| Jose        | Offerman      |
| Jose        | Melendez      |
| Jose        | Escobar       |
| Jose        | Mota          |
| Jose        | Tolentino     |
| Jose        | Hernandez     |
| Jose        | Valentin      |
| Jose        | Lima          |
| Jose        | Martinez      |
| Jose        | Mercedes      |
| Jose        | Oliva         |
| Jose        | Alberro       |
| Jose        | Parra         |
| Jose        | Herrera       |
| Jose        | Paniagua      |
| Jose        | Malave        |
| Jose        | Silva         |
| Jose        | Guillen       |
| Jose        | Cruz          |
| Jose        | Santiago      |
| Jose        | Vidro         |
| Jose        | Cabrera       |
| Jose        | Nieves        |
| Jose        | Jimenez       |
| Jose        | Macias        |
| Jose        | Fernandez     |
| Jose        | Molina        |
| Jose        | Rodriguez     |
| Jose        | Ortiz         |
| Jose        | Nunez         |
| Jose        | Acevedo       |
| Jose        | Leon          |
| Jose        | Contreras     |
| Jose        | Morban        |
| Jose        | Valverde      |
| Jose        | Reyes         |
| Jose        | Bautista      |
| Jose        | Castillo      |
| Jose        | Lopez         |
| Jose        | Capellan      |
| Jose        | Veras         |
| Jose        | Diaz          |
| Jose        | Garcia        |
| Jose        | Reyes         |
| Jose        | Ascanio       |
| Jose        | Morales       |
| Jose        | Arredondo     |
| Jose        | Mijares       |
| Jose        | Lobaton       |
| Jose        | Tabata        |
| Jose        | Ceda          |
| Jose        | Valdez        |
| Jose        | Iglesias      |
| Jose        | Altuve        |
| Jose        | Constanza     |
| Jose        | Quintana      |
| Jose        | Ortega        |
| Jose        | Fernandez     |
| Jose        | Cisnero       |
| Jose        | De La Torre   |
| Jose        | Alvarez       |
| Jose        | Dominguez     |
| Jose        | Ramirez       |
| Jose        | Abreu         |
| Jose        | Ramirez       |
| Jose        | Pirela        |
| Jose        | Urena         |
| Jose        | De Paula      |
| Jose        | Valdez        |
| Jose        | Peraza        |
| Jose        | Berrios       |
| Jose        | Leclerc       |
| Jose        | Rondon        |
| Jose        | De Leon       |
| Jose        | Martinez      |
| Jose        | Torres        |
| Jose        | Osuna         |
| Jose        | Alvarado      |
| Jose        | Ruiz          |
| Jose        | Briceno       |
| Jose        | Castillo      |
| Jose        | Fernandez     |
| Jose        | Fernandez     |
| Jose        | Quijada       |
| Jose        | Suarez        |
| Jose        | Urquidy       |
| Jose        | Rodriguez     |
| Jose        | Barrero       |
| Jose        | Mujica        |
| Jose        | Devers        |
| Jose        | Godoy         |
| Jose        | Marte         |
| Jose        | Siri          |
| Jose        | Azocar        |
| Jose        | Herrera       |
| Jose        | Miranda       |
| Jose        | Cuas          |
| Jose        | Butto         |
| Jose        | Hernandez     |
| Jose        | Caballero     |
| Jose        | Mendez        |
| Josef       | Koukalik      |
| Josh        | Barfield      |
| Josh        | Spence        |
| Josh        | Naylor        |
| Josias      | Manzanillo    |
| Josmil      | Pinto         |
| Jovani      | Moran         |
| Juan        | Delis         |
| Juan        | Pizarro       |
| Juan        | Marichal      |
| Juan        | Rios          |
| Juan        | Beniquez      |
| Juan        | Jimenez       |
| Juan        | Bernhardt     |
| Juan        | Berenguer     |
| Juan        | Bonilla       |
| Juan        | Agosto        |
| Juan        | Espino        |
| Juan        | Samuel        |
| Juan        | Nieves        |
| Juan        | Castillo      |
| Juan        | Gonzalez      |
| Juan        | Bell          |
| Juan        | Guzman        |
| Juan        | Guerrero      |
| Juan        | Castillo      |
| Juan        | Acevedo       |
| Juan        | Castro        |
| Juan        | Encarnacion   |
| Juan        | Pena          |
| Juan        | Sosa          |
| Juan        | Melo          |
| Juan        | Uribe         |
| Juan        | Moreno        |
| Juan        | Rincon        |
| Juan        | Cruz          |
| Juan        | Rivera        |
| Juan        | Brito         |
| Juan        | Diaz          |
| Juan        | Dominguez     |
| Juan        | Cerros        |
| Juan        | Padilla       |
| Juan        | Mateo         |
| Juan        | Salas         |
| Juan        | Perez         |
| Juan        | Lara          |
| Juan        | Morillo       |
| Juan        | Miranda       |
| Juan        | Francisco     |
| Juan        | Nicasio       |
| Juan        | Abreu         |
| Juan        | Diaz          |
| Juan        | Lagares       |
| Juan        | Perez         |
| Juan        | Centeno       |
| Juan        | Jaime         |
| Juan        | Minaya        |
| Juan        | Graterol      |
| Juan        | Soto          |
| Juan        | Yepez         |
| Juan        | Then          |
| Juan Carlos | Oviedo        |
| Judge       | Fuchs         |
| Julian      | Javier        |
| Julian      | Tavarez       |
| Julian      | Fernandez     |
| Julio       | Bonetti       |
| Julio       | Gonzalez      |
| Julio       | Moreno        |
| Julio       | Becquer       |
| Julio       | Gotay         |
| Julio       | Navarro       |
| Julio       | Gonzalez      |
| Julio       | Valdez        |
| Julio       | Franco        |
| Julio       | Solano        |
| Julio       | Machado       |
| Julio       | Valera        |
| Julio       | Peguero       |
| Julio       | Mosquera      |
| Julio       | Santana       |
| Julio       | Ramirez       |
| Julio       | Zuleta        |
| Julio       | Lugo          |
| Julio       | Mateo         |
| Julio       | Manon         |
| Julio       | De Paula      |
| Julio       | Teheran       |
| Julio       | Urias         |
| Julio       | Rodriguez     |
| Jumbo       | Diaz          |
| Jung        | Bong          |
| Jung Ho     | Kang          |
| Junichi     | Tazawa        |
| Juniel      | Querecuto     |
| Junior      | Ortiz         |
| Junior      | Noboa         |
| Junior      | Felix         |
| Junior      | Lake          |
| Junior      | Guerra        |
| Junior      | Fernandez     |
| Jurickson   | Profar        |
| Justin      | Morneau       |
| Justin      | Huber         |
| Justin      | Masterson     |
| Justin      | Lawrence      |
| Karim       | Garcia        |
| Kazuhiro    | Sasaki        |
| Kazuhisa    | Ishii         |
| Kazuhisa    | Makita        |
| Kazuhito    | Tadano        |
| Kazuo       | Matsui        |
| Kazuo       | Fukumori      |
| Kei         | Igawa         |
| Keibert     | Ruiz          |
| Keiichi     | Yabu          |
| Keith       | Lampard       |
| Keith       | McDonald      |
| Kelvim      | Escobar       |
| Kelvin      | Jimenez       |
| Kelvin      | Herrera       |
| Kelvin      | Marte         |
| Kelvin      | Gutierrez     |
| Ken         | MacKenzie     |
| Ken         | Crosby        |
| Ken         | Takahashi     |
| Kendry      | Flores        |
| Kendrys     | Morales       |
| Kenji       | Johjima       |
| Kenley      | Jansen        |
| Kennys      | Vargas        |
| Kenshin     | Kawakami      |
| Kensuke     | Tanaka        |
| Kenta       | Maeda         |
| Kervin      | Castro        |
| Ketel       | Marte         |
| Keury       | Mella         |
| Kevin       | Nicholson     |
| Kid         | Summers       |
| Kiko        | Calero        |
| Kirk        | McCaskill     |
| Klondike    | Smith         |
| Kodai       | Senga         |
| Kohei       | Arihara       |
| Koji        | Uehara        |
| Kosuke      | Fukudome      |
| Kurt        | Krieger       |
| Kwang Hyun  | Kim           |
| Kyuji       | Fujikawa      |
| Lance          | Painter       |
| Lariel         | Gonzalez      |
| Larry          | Ressler       |
| Larry          | Murphy        |
| Larry          | McLean        |
| Larry          | Landreth      |
| Larry          | Walker        |
| Lendy          | Castillo      |
| Lenyn          | Sosa          |
| Leo            | Cardenas      |
| Leo            | Posada        |
| Leo            | Sutherland    |
| Leo            | Hernandez     |
| Leo            | Garcia        |
| Leo            | Gomez         |
| Leo            | Estrella      |
| Leody          | Taveras       |
| Leonel         | Campos        |
| Leonys         | Martin        |
| Les            | Rohr          |
| Les            | Straker       |
| Leslie         | Brea          |
| Lester         | Oliveros      |
| Leury          | Garcia        |
| Lewin          | Diaz          |
| Lewis          | Thorpe        |
| Leyson         | Septimo       |
| Liam           | Hendriks      |
| Lino           | Donoso        |
| Lino           | Urdaneta      |
| Liover         | Peguero       |
| Lisalverto     | Bonilla       |
| Liu            | Rodriguez     |
| Livan          | Hernandez     |
| Livan          | Soto          |
| Lorencito      | Fernandez     |
| Lorenzo        | Barcelo       |
| Lou            | Paul          |
| Lou            | Castro        |
| Lou            | Polli         |
| Lourdes        | Gurriel       |
| Lucius         | Fox           |
| Luis           | Olmo          |
| Luis           | Suarez        |
| Luis           | Aloma         |
| Luis           | Marquez       |
| Luis           | Arroyo        |
| Luis           | Aparicio      |
| Luis           | Tiant         |
| Luis           | Alcaraz       |
| Luis           | Alvarado      |
| Luis           | Peraza        |
| Luis           | Melendez      |
| Luis           | Gomez         |
| Luis           | Quintana      |
| Luis           | Delgado       |
| Luis           | Rosado        |
| Luis           | Pujols        |
| Luis           | Silverio      |
| Luis           | Aguayo        |
| Luis           | Leal          |
| Luis           | Salazar       |
| Luis           | Aponte        |
| Luis           | Sanchez       |
| Luis           | DeLeon        |
| Luis           | Quinones      |
| Luis           | Rivera        |
| Luis           | Aquino        |
| Luis           | Polonia       |
| Luis           | Alicea        |
| Luis           | de los Santos |
| Luis           | Sojo          |
| Luis           | Encarnacion   |
| Luis           | Mercedes      |
| Luis           | Ortiz         |
| Luis           | Lopez         |
| Luis           | Andujar       |
| Luis           | Castillo      |
| Luis           | Ordaz         |
| Luis           | Garcia        |
| Luis           | Vizcaino      |
| Luis           | Rivera        |
| Luis           | Matos         |
| Luis           | Saturria      |
| Luis           | Rivas         |
| Luis           | Figueroa      |
| Luis           | Pineda        |
| Luis           | Ugueto        |
| Luis           | Garcia        |
| Luis           | de los Santos |
| Luis           | Ayala         |
| Luis           | Terrero       |
| Luis           | Martinez      |
| Luis           | Gonzalez      |
| Luis           | Rodriguez     |
| Luis           | Hernandez     |
| Luis           | Mendoza       |
| Luis           | Montanez      |
| Luis           | Maza          |
| Luis           | Cruz          |
| Luis           | Valbuena      |
| Luis           | Perdomo       |
| Luis           | Durango       |
| Luis           | Atilano       |
| Luis           | Perez         |
| Luis           | Marte         |
| Luis           | Avilan        |
| Luis           | Jimenez       |
| Luis           | Jimenez       |
| Luis           | Garcia        |
| Luis           | Sardinas      |
| Luis           | Severino      |
| Luis           | Perdomo       |
| Luis           | Cessa         |
| Luis           | Torrens       |
| Luis           | Castillo      |
| Luis           | Santos        |
| Luis           | Guillorme     |
| Luis           | Urias         |
| Luis           | Rengifo       |
| Luis           | Arraez        |
| Luis           | Escobar       |
| Luis           | Robert        |
| Luis           | Patino        |
| Luis           | Gonzalez      |
| Luis           | Garcia        |
| Luis           | Oviedo        |
| Luis           | Madero        |
| Luis           | Barrera       |
| Luis           | Marte         |
| Luis           | Gil           |
| Luis           | Frias         |
| Luis           | Castillo      |
| Luis           | Liberato      |
| Luis           | Ortiz         |
| Luis           | Medina        |
| Luis           | Rojas         |
| Luis Alexander | Basabe        |
| Luiz           | Gohara        |
| Luke           | Prokopec      |
| Luke           | Hughes        |
| Mac            | MacArthur     |
| Mac            | Suzuki        |
| Magglio        | Ordonez       |
| Magneuris      | Sierra        |
| Maicer         | Izturis       |
| Maikel         | Cleto         |
| Maikel         | Franco        |
| Maikel         | Garcia        |
| Manny          | Montejo       |
| Manny          | Jimenez       |
| Manny          | Mota          |
| Manny          | Sanguillen    |
| Manny          | Muniz         |
| Manny          | Trillo        |
| Manny          | Sarmiento     |
| Manny          | Castillo      |
| Manny          | Hernandez     |
| Manny          | Alexander     |
| Manny          | Ramirez       |
| Manny          | Martinez      |
| Manny          | Aybar         |
| Manny          | Corpas        |
| Manny          | Acosta        |
| Manny          | Pina          |
| Manny          | Banuelos      |
| Manny          | Acta          |
| Manuel         | Cueto         |
| Manuel         | Lee           |
| Manuel         | Barrios       |
| Manuel         | Margot        |
| Manuel         | Rodriguez     |
| Marcelino      | Solis         |
| Marcelino      | Lopez         |
| Marcell        | Ozuna         |
| Marco          | Scutaro       |
| Marco          | Estrada       |
| Marco          | Hernandez     |
| Marcos         | Armas         |
| Marcos         | Carvajal      |
| Marcos         | Mateo         |
| Marcos         | Diplan        |
| Mariano        | Duncan        |
| Mariano        | Rivera        |
| Marino         | Pieretti      |
| Marino         | Santana       |
| Marino         | Salas         |
| Mario          | Guerrero      |
| Mario          | Mendoza       |
| Mario          | Soto          |
| Mario          | Ramirez       |
| Mario          | Diaz          |
| Mario          | Valdez        |
| Mario          | Encarnacion   |
| Mario          | Feliciano     |
| Mark           | Ettles        |
| Mark           | Hutton        |
| Martin         | Malone        |
| Martin         | Prado         |
| Martin         | Maldonado     |
| Martin         | Perez         |
| Martin         | Dihigo        |
| Marty          | Swandell      |
| Marty          | Hogan         |
| Marty          | Krug          |
| Marty          | Martinez      |
| Marvin         | Benard        |
| Marwin         | Gonzalez      |
| Masahide       | Kobayashi     |
| Masahiro       | Tanaka        |
| Masanori       | Murakami      |
| Masao          | Kida          |
| Masataka       | Yoshida       |
| Masato         | Yoshii        |
| Masumi         | Kuwata        |
| Matias         | Carrillo      |
| Matt           | Stairs        |
| Matt           | Maysey        |
| Matt           | Brash         |
| Matty          | Alou          |
| Mauricio       | Robles        |
| Mauricio       | Cabrera       |
| Mauricio       | Dubon         |
| Mauricio       | Llovera       |
| Mauro          | Zarate        |
| Mauro          | Gomez         |
| Max            | Leon          |
| Max            | Ramirez       |
| Max            | St. Pierre    |
| Max            | Kepler        |
| Max            | Castillo      |
| Mayckol        | Guaipe        |
| Meibrys        | Viloria       |
| Mel            | Kerr          |
| Mel            | Almada        |
| Mel            | Rojas         |
| Melido         | Perez         |
| Melky          | Cabrera       |
| Melky          | Mesa          |
| Melvin         | Nieves        |
| Melvin         | Rosario       |
| Melvin         | Mora          |
| Melvin         | Dorta         |
| Melvin         | Mercedes      |
| Memo           | Luna          |
| Mendy          | Lopez         |
| Merandy        | Gonzalez      |
| Merito         | Acosta        |
| Merkin         | Valdez        |
| Michael        | Campbell      |
| Michael        | Tejera        |
| Michael        | Saunders      |
| Michael        | Martinez      |
| Michael        | Pineda        |
| Michael        | Feliz         |
| Michael        | Ynoa          |
| Michael        | Soroka        |
| Michael        | Perez         |
| Micheal        | Nakamura      |
| Michel         | Hernandez     |
| Michel         | Baez          |
| Mickey         | Scott         |
| Midre          | Cummings      |
| Migel          | Puente        |
| Miguel         | de la Hoz     |
| Miguel         | Fuentes       |
| Miguel         | Dilone        |
| Miguel         | Garcia        |
| Miguel         | Batista       |
| Miguel         | Mejia         |
| Miguel         | Cairo         |
| Miguel         | Tejada        |
| Miguel         | Del Toro      |
| Miguel         | Asencio       |
| Miguel         | Olivo         |
| Miguel         | Ojeda         |
| Miguel         | Cabrera       |
| Miguel         | Perez         |
| Miguel         | Montero       |
| Miguel         | Gonzalez      |
| Miguel         | Socolovich    |
| Miguel         | Gonzalez      |
| Miguel         | Rojas         |
| Miguel         | Gonzalez      |
| Miguel         | Castro        |
| Miguel         | Sano          |
| Miguel         | Almonte       |
| Miguel         | Diaz          |
| Miguel         | Andujar       |
| Miguel         | Gomez         |
| Miguel         | Del Pozo      |
| Miguel         | Yajure        |
| Miguel         | Sanchez       |
| Miguel         | Aguilar       |
| Miguel         | Vargas        |
| Miguel         | Amaya         |
| Mike           | Muldoon       |
| Mike           | Hines         |
| Mike           | Jones         |
| Mike           | Flynn         |
| Mike           | O'Neill       |
| Mike           | Hopkins       |
| Mike           | Gonzalez      |
| Mike           | Herrera       |
| Mike           | Guerra        |
| Mike           | Fornieles     |
| Mike           | Cuellar       |
| Mike           | Kilkenny      |
| Mike           | Eden          |
| Mike           | Blowers       |
| Mike           | Perez         |
| Mike           | Gardiner      |
| Mike           | Johnson       |
| Mike           | Lowell        |
| Mike           | Rivera        |
| Mike           | Nickeas       |
| Mike           | Scanlon       |
| Mike           | Shildt        |
| Mike           | Walsh         |
| Milt           | Whitehead     |
| Milt           | Ramirez       |
| Minnie         | Minoso        |
| Minnie         | Rojas         |
| Minnie         | Mendoza       |
| Moe            | Drabowsky     |
| Moises         | Sierra        |
| Molly          | Moore         |
| Munenori       | Kawasaki      |
| Nabil          | Crismatt      |
| Nap            | Reyes         |
| Napoleon       | Calzado       |
| Narciso        | Elvira        |
| Narciso        | Crook         |
| Ned            | Crompton      |
| Nefi           | Ogando        |
| Neftali        | Feliz         |
| Neftali        | Soto          |
| Neifi          | Perez         |
| Nelson         | Norman        |
| Nelson         | Liriano       |
| Nelson         | Santovenia    |
| Nelson         | Cruz          |
| Nelson         | Cruz          |
| Nelson         | Velazquez     |
| Nerio          | Rodriguez     |
| Nestor         | Chavez        |
| Nestor         | Cortes        |
| Newt           | Randall       |
| Nick           | Pivetta       |
| Nigel          | Wilson        |
| Nino           | Escalera      |
| Nino           | Espinosa      |
| Niuman         | Romero        |
| Nivaldo        | Rodriguez     |
| Noe            | Munoz         |
| Noel           | Cuevas        |
| Nomar          | Mazara        |
| Norberto       | Martin        |
| Norge          | Ruiz          |
| Nori           | Aoki          |
| Norihiro       | Nakamura      |
| Octavio        | Dotel         |
| Odalis         | Perez         |
| Odrisamer      | Despaigne     |
| Odubel         | Herrera       |
| Olaf           | Henriksen     |
| Oliver         | Perez         |
| Oliver         | Ortega        |
| Oliverio       | Ortiz         |
| Olmedo         | Saenz         |
| Omar           | Moreno        |
| Omar           | Vizquel       |
| Omar           | Olivares      |
| Omar           | Daal          |
| Omar           | Infante       |
| Omar           | Beltre        |
| Omar           | Narvaez       |
| Omir           | Santos        |
| Oneil          | Cruz          |
| Onelki         | Garcia        |
| Onix           | Concepcion    |
| Orber          | Moreno        |
| Oreste         | Marrero       |
| Orestes        | Destrade      |
| Orlando        | Cepeda        |
| Orlando        | Pena          |
| Orlando        | McFarlane     |
| Orlando        | Alvarez       |
| Orlando        | Ramirez       |
| Orlando        | Gonzalez      |
| Orlando        | Isales        |
| Orlando        | Sanchez       |
| Orlando        | Mercado       |
| Orlando        | Merced        |
| Orlando        | Miller        |
| Orlando        | Cabrera       |
| Orlando        | Hernandez     |
| Orlando        | Calixte       |
| Orlando        | Arcia         |
| Oscar          | Tuero         |
| Oscar          | Estrada       |
| Oscar          | Judd          |
| Oscar          | Zamora        |
| Oscar          | Azocar        |
| Oscar          | Henriquez     |
| Oscar          | Salazar       |
| Oscar          | Villarreal    |
| Oscar          | Robles        |
| Oscar          | Taveras       |
| Oscar          | Hernandez     |
| Oscar          | Mercado       |
| Oscar          | Gonzalez      |
| Oscar          | Colas         |
| Osiris         | Matos         |
| Osmer          | Morales       |
| Ossie          | Alvarez       |
| Ossie          | Chavarria     |
| Ossie          | Blanco        |
| Osvaldo        | Fernandez     |
| Osvaldo        | Martinez      |
| Oswald         | Peraza        |
| Oswaldo        | Peraza        |
| Oswaldo        | Mairena       |
| Oswaldo        | Navarro       |
| Oswaldo        | Arcia         |
| Oswaldo        | Cabrera       |
| Otto           | Deininger     |
| Otto           | Hess          |
| Otto           | Velez         |
| Otto           | Lopez         |
| Ozzie          | Van Brabant   |
| Ozzie          | Virgil        |
| Ozzie          | Virgil        |
| Ozzie          | Guillen       |
| Ozzie          | Canseco       |
| Ozzie          | Albies        |
| P. J.          | Conlon        |
| Pablo          | Torrealba     |
| Pablo          | Martinez      |
| Pablo          | Ozuna         |
| Pablo          | Sandoval      |
| Pablo          | Lopez         |
| Pablo          | Reyes         |
| Paddy          | O'Connor      |
| Pancho         | Herrera       |
| Paolo          | Espino        |
| Pascual        | Perez         |
| Pascual        | Matos         |
| Pasqual        | Coco          |
| Pat            | McGee         |
| Pat            | McManus       |
| Pat            | Scanlon       |
| Pat            | Lyons         |
| Pat            | Hannivan      |
| Pat            | Scantlebury   |
| Patrick        | O'Loughlin    |
| Patrick        | Horan         |
| Patsy          | Donovan       |
| Paul           | Krichell      |
| Paul           | Calvert       |
| Paul           | Casanova      |
| Paul           | Hodgson       |
| Paul           | Marak         |
| Paul           | Quantrill     |
| Paul           | Spoljaric     |
| Paulo          | Orlando       |
| Pedro          | Dibut         |
| Pedro          | Ramos         |
| Pedro          | Gonzalez      |
| Pedro          | Borbon        |
| Pedro          | Garcia        |
| Pedro          | Guerrero      |
| Pedro          | Munoz         |
| Pedro          | Astacio       |
| Pedro          | Martinez      |
| Pedro          | Borbon        |
| Pedro          | Castellano    |
| Pedro          | Martinez      |
| Pedro          | Valdes        |
| Pedro          | Feliz         |
| Pedro          | Santana       |
| Pedro          | Feliciano     |
| Pedro          | Liriano       |
| Pedro          | Lopez         |
| Pedro          | Strop         |
| Pedro          | Viola         |
| Pedro          | Alvarez       |
| Pedro          | Ciriaco       |
| Pedro          | Beato         |
| Pedro          | Florimon      |
| Pedro          | Figueroa      |
| Pedro          | Hernandez     |
| Pedro          | Baez          |
| Pedro          | Severino      |
| Pedro          | Araujo        |
| Pedro          | Avila         |
| Pepe           | Mangual       |
| Pepe           | Frias         |
| Pete           | Donnelly      |
| Pete           | Morris        |
| Pete           | Wood          |
| Pete           | Daniels       |
| Pete           | Hasney        |
| Pete           | LePine        |
| Pete           | Ward          |
| Pete           | Craig         |
| Pete           | Hernandez     |
| Pete           | LaForest      |
| Pete           | Orr           |
| Peter          | Hoy           |
| Peter          | Moylan        |
| Phil           | Routcliffe    |
| Phil           | Marchildon    |
| Phil           | Stockman      |
| Phillippe      | Aumont        |
| Phillips       | Valdez        |
| Phoenix        | Sanders       |
| Placido        | Polanco       |
| Pompeyo        | Davalillo     |
| Pop            | Smith         |
| Porfi          | Altamirano    |
| Preston        | Gomez         |
| Pretzels       | Getzien       |
| Quilvio        | Veras         |
| R. J.          | Swindle       |
| Radhames       | Dykhoff       |
| Radhames       | Liz           |
| Rafael         | Almeida       |
| Rafael         | Robles        |
| Rafael         | Batista       |
| Rafael         | Landestoy     |
| Rafael         | Vasquez       |
| Rafael         | Santo Domingo |
| Rafael         | Ramirez       |
| Rafael         | Belliard      |
| Rafael         | Santana       |
| Rafael         | Montalvo      |
| Rafael         | Palmeiro      |
| Rafael         | Valdez        |
| Rafael         | Bournigal     |
| Rafael         | Carmona       |
| Rafael         | Quirico       |
| Rafael         | Medina        |
| Rafael         | Roque         |
| Rafael         | Furcal        |
| Rafael         | Soriano       |
| Rafael         | Betancourt    |
| Rafael         | Perez         |
| Rafael         | Rodriguez     |
| Rafael         | Dolis         |
| Rafael         | Ortega        |
| Rafael         | Montero       |
| Rafael         | Ynoa          |
| Rafael         | Bautista      |
| Rafael         | Devers        |
| Rafael         | Marchan       |
| Raimel         | Tapia         |
| Raisel         | Iglesias      |
| Ralph          | Buxton        |
| Ralph          | McCabe        |
| Ralph          | Milliard      |
| Ramiro         | Mendoza       |
| Ramiro         | Pena          |
| Ramon          | Garcia        |
| Ramon          | Monzant       |
| Ramon          | Conde         |
| Ramon          | Lopez         |
| Ramon          | Hernandez     |
| Ramon          | Webster       |
| Ramon          | de los Santos |
| Ramon          | Aviles        |
| Ramon          | Romero        |
| Ramon          | Martinez      |
| Ramon          | Pena          |
| Ramon          | Manon         |
| Ramon          | Garcia        |
| Ramon          | Caraballo     |
| Ramon          | Morel         |
| Ramon          | Fermin        |
| Ramon          | Tatis         |
| Ramon          | Hernandez     |
| Ramon          | Ortiz         |
| Ramon          | Castro        |
| Ramon          | Vazquez       |
| Ramon          | Santiago      |
| Ramon          | Nivar         |
| Ramon          | Castro        |
| Ramon          | Ramirez       |
| Ramon          | Troncoso      |
| Ramon          | Ramirez       |
| Ramon          | Flores        |
| Ramon          | Cabrera       |
| Ramon          | Torres        |
| Ramon          | Laureano      |
| Ramon          | Rosso         |
| Ramon          | Urias         |
| Randall        | Simon         |
| Randall        | Delgado       |
| Randor         | Bierd         |
| Randy          | Rosario       |
| Randy          | Arozarena     |
| Randy          | Vasquez       |
| Rangel         | Ravelo        |
| Ranger         | Suarez        |
| Raudel         | Lazo          |
| Raudy          | Read          |
| Raul           | Sanchez       |
| Raul           | Mondesi       |
| Raul           | Casanova      |
| Raul           | Chavez        |
| Raul           | Gonzalez      |
| Raul           | Valdes        |
| Raul           | Alcantara     |
| Ravelo         | Manzanillo    |
| Ray            | Noble         |
| Ray            | Daviault      |
| Ray            | Olmedo        |
| Raynel         | Espinal       |
| Red            | Connally      |
| Red            | Long          |
| Reddy          | Mack          |
| Reggie         | Richter       |
| Reggie         | Otero         |
| Reggie         | Cleveland     |
| Reiver         | Sanmartin     |
| Remy           | Hermoso       |
| Renato         | Nunez         |
| Rene           | Monteagudo    |
| Rene           | Valdes        |
| Rene           | Arocha        |
| Rene           | Reyes         |
| Rene           | Rivera        |
| Rene           | Tosoni        |
| Rene           | Pinto         |
| Rennie         | Stennett      |
| Reno           | Bertoia       |
| Renyel         | Pinto         |
| Reuben         | Ewing         |
| Rey            | Quinones      |
| Rey            | Sanchez       |
| Rey            | Ordonez       |
| Rey            | Navarro       |
| Reyes          | Moronta       |
| Reymin         | Guduan        |
| Reynaldo       | Garcia        |
| Reynaldo       | Lopez         |
| Rheal          | Cormier       |
| Rhiner         | Cruz          |
| Ricardo        | Torres        |
| Ricardo        | Rincon        |
| Ricardo        | Rodriguez     |
| Ricardo        | Pinto         |
| Ricardo        | Rodriguez     |
| Ricardo        | Sanchez       |
| Rich           | Garces        |
| Rich           | Butler        |
| Rich           | Harden        |
| Rich           | Thompson      |
| Richard        | Hidalgo       |
| Richard        | Urena         |
| Richard        | Rodriguez     |
| Rick           | Joseph        |
| Rick           | Lisi          |
| Rick           | van den Hurk  |
| Ricky          | Bones         |
| Ricky          | Otero         |
| Ricky          | Ledee         |
| Rico           | Carty         |
| Rico           | Rossy         |
| Rigo           | Beltran       |
| Rikkert        | Faneyte       |
| Roansy         | Contreras     |
| Rob            | Belloir       |
| Rob            | Ducey         |
| Rob            | Butler        |
| Rob            | Tejeda        |
| Rob            | Refsnyder     |
| Rob            | Zastryzny     |
| Rob            | Thomson       |
| Robel          | Garcia        |
| Robert         | Brown         |
| Robert         | Eenhoorn      |
| Robert         | Perez         |
| Robert         | Machado       |
| Robert         | Suarez        |
| Roberto        | Ortiz         |
| Roberto        | Clemente      |
| Roberto        | Vargas        |
| Roberto        | Pena          |
| Roberto        | Rodriguez     |
| Roberto        | Kelly         |
| Roberto        | Alomar        |
| Roberto        | Hernandez     |
| Roberto        | Mejia         |
| Roberto        | Petagine      |
| Roberto        | Rivera        |
| Roberto        | Duran         |
| Roberto        | Ramirez       |
| Roberto        | Novoa         |
| Roberto        | Hernandez     |
| Roberto        | Perez         |
| Roberto        | Osuna         |
| Roberto        | Gomez         |
| Robin          | Jennings      |
| Robinson       | Checo         |
| Robinson       | Cancel        |
| Robinson       | Cano          |
| Robinson       | Chirinos      |
| Robinson       | Leyer         |
| Robinzon       | Diaz          |
| Rod            | Carew         |
| Rodolfo        | Castro        |
| Rodrigo        | Lopez         |
| Rodrigo        | Rosario       |
| Roenis         | Elias         |
| Rogelio        | Martinez      |
| Rogelio        | Alvarez       |
| Rogelio        | Armenteros    |
| Roger          | Moret         |
| Roger          | Cedeno        |
| Roger          | Deago         |
| Roger          | Bernadina     |
| Roland         | Gladu         |
| Rolando        | Roomes        |
| Rolando        | Arrojo        |
| Roman          | Mejias        |
| Roman          | Colon         |
| Roman          | Mendez        |
| Romulo         | Sanchez       |
| Ron            | Piche         |
| Ron            | Taylor        |
| Ron            | Law           |
| Ron            | Gardenhire    |
| Ronald         | Belisario     |
| Ronald         | Torreyes      |
| Ronald         | Herrera       |
| Ronald         | Guzman        |
| Ronald         | Acuna         |
| Ronald         | Bolanos       |
| Ronel          | Blanco        |
| Ronny          | Cedeno        |
| Ronny          | Paulino       |
| Ronny          | Rodriguez     |
| Ronny          | Henriquez     |
| Rony           | Garcia        |
| Rosario        | Rodriguez     |
| Rosell         | Herrera       |
| Rosman         | Garcia        |
| Rougned        | Odor          |
| Rowan          | Wick          |
| Roy            | Valdes        |
| Rubby          | De La Rosa    |
| Rube           | Schauer       |
| Ruben          | Gomez         |
| Ruben          | Amaro         |
| Ruben          | Sierra        |
| Ruben          | Rodriguez     |
| Ruben          | Rivera        |
| Ruben          | Mateo         |
| Ruben          | Quevedo       |
| Ruben          | Gotay         |
| Ruben          | Tejada        |
| Ruddy          | Lugo          |
| Rudy           | Arias         |
| Rudy           | Hernandez     |
| Rudy           | Hernandez     |
| Rudy           | Pemberton     |
| Rufino         | Linares       |
| Rugger         | Ardizoia      |
| Runelvys       | Hernandez     |
| Rupe           | Toppin        |
| Rusney         | Castillo      |
| Russ           | Ford          |
| Russell        | Martin        |
| Rusty          | Torres        |
| Ryan           | Radmanovich   |
| Ryan           | Dempster      |
| Ryan           | Braun         |
| Ryan           | Rowland-Smith |
| Rymer          | Liriano       |
| Rynie          | Wolters       |
| Ryota          | Igarashi      |
| Salome         | Barojas       |
| Salomon        | Torres        |
| Salvador       | Perez         |
| Sam            | Jackson       |
| Sam            | LaRocque      |
| Sam            | Nicholl       |
| Sam            | White         |
| Sam            | Parrilla      |
| Sam            | Mejias        |
| Sam            | Deduno        |
| Sammy          | Sosa          |
| Sammy          | Gervacio      |
| Sandy          | Ullrich       |
| Sandy          | Consuegra     |
| Sandy          | Amoros        |
| Sandy          | Alomar        |
| Sandy          | Valdespino    |
| Sandy          | Alomar        |
| Sandy          | Martinez      |
| Sandy          | Rosario       |
| Sandy          | Leon          |
| Sandy          | Alcantara     |
| Sandy          | Baez          |
| Sang-Hoon      | Lee           |
| Santiago       | Rosario       |
| Santiago       | Guzman        |
| Santiago       | Perez         |
| Santiago       | Casilla       |
| Santiago       | Ramirez       |
| Santiago       | Espinal       |
| Santo          | Alcala        |
| Satoru         | Komiyama      |
| Saul           | Rivera        |
| Scott          | Mathieson     |
| Scott          | Thorman       |
| Scott          | Richmond      |
| Scott          | Diamond       |
| Sean           | Reid-Foley    |
| Sebastian      | Rivero        |
| Seiya          | Suzuki        |
| Sendy          | Rleal         |
| Seranthony     | Dominguez     |
| Sergio         | Robles        |
| Sergio         | Ferrer        |
| Sergio         | Valdez        |
| Sergio         | Escalona      |
| Sergio         | Alcantara     |
| Seunghwan      | Oh            |
| Severino       | Gonzalez      |
| Shairon        | Martis        |
| Shane          | Lindsay       |
| Shawn          | Hill          |
| Shayne         | Bennett       |
| Sherman        | Obando        |
| Sherry         | Robertson     |
| Sherten        | Apostel       |
| Shigetoshi     | Hasegawa      |
| Shin-Soo       | Choo          |
| Shingo         | Takatsu       |
| Shintaro       | Fujinami      |
| Shogo          | Akiyama       |
| Shohei         | Ohtani        |
| Shorty         | Dee           |
| Shun           | Yamaguchi     |
| Sid            | Monge         |
| Sidney         | Ponson        |
| Sil            | Campusano     |
| Silvino        | Bracho        |
| Silvio         | Martinez      |
| Sim            | Bullas        |
| Simon          | Pond          |
| Simon          | Castro        |
| Simon          | Muzziotti     |
| Sixto          | Lezcano       |
| Sixto          | Sanchez       |
| Skel           | Roach         |
| Sleeper        | Sullivan      |
| So             | Taguchi       |
| Socrates       | Brito         |
| Spud           | Johnson       |
| Stan           | Javier        |
| Starlin        | Castro        |
| Starling       | Marte         |
| Stefan         | Wever         |
| Steve          | Bellan        |
| Steve          | Dunn          |
| Steve          | Jeltz         |
| Steve          | Wilson        |
| Steve          | Chitren       |
| Steve          | Sinclair      |
| Steve          | Green         |
| Steve          | Torrealba     |
| Steve          | Kent          |
| Steve          | Randolph      |
| Steven         | Moya          |
| Stolmy         | Pimentel      |
| Stubby         | Clapp         |
| Sugar Ray      | Marimon       |
| Sun-Woo        | Kim           |
| Tadahito       | Iguchi        |
| Takahito       | Nomura        |
| Takashi        | Kashiwada     |
| Takashi        | Saito         |
| Tavo           | Alvarez       |
| Tayler         | Scott         |
| Taylor         | Green         |
| Tayron         | Guerrero      |
| Ted            | Sullivan      |
| Ted            | Lewis         |
| Ted            | Bowsfield     |
| Ted            | Martinez      |
| Teddy          | Higuera       |
| Teoscar        | Hernandez     |
| Terry          | Puhl          |
| Thairo         | Estrada       |
| The Only       | Nolan         |
| Thomas         | Maguire       |
| Thyago         | Vieira        |
| Tilson         | Brito         |
| Tim            | Manning       |
| Tim            | Harkness      |
| Timo           | Perez         |
| Tip            | O'Neill       |
| Tito           | Fuentes       |
| Tito           | Navarro       |
| Tobi           | Stoner        |
| Toby           | Hernandez     |
| Tom            | Smith         |
| Tom            | Brown         |
| Tom            | Dowse         |
| Tom            | Needham       |
| Tom            | Daly          |
| Tom            | Burgess       |
| Tom            | Hughes        |
| Tom            | Harrison      |
| Tom            | Silverio      |
| Tom            | Waddell       |
| Tom            | McCarthy      |
| Tom            | Mastny        |
| Tomas          | Perez         |
| Tomas          | de la Rosa    |
| Tomas          | Telis         |
| Tomas          | Nido          |
| Tommy          | Bond          |
| Tommy          | Casey         |
| Tommy          | de la Cruz    |
| Tommy          | Cruz          |
| Tommy          | Phelps        |
| Tommy          | Connolly      |
| Tomo           | Ohka          |
| Tony           | Mullane       |
| Tony           | Welzer        |
| Tony           | Ordenana      |
| Tony           | Taylor        |
| Tony           | Curry         |
| Tony           | Gonzalez      |
| Tony           | Oliva         |
| Tony           | Martinez      |
| Tony           | Perez         |
| Tony           | Solaita       |
| Tony           | Armas         |
| Tony           | Chevez        |
| Tony           | Bernazard     |
| Tony           | Pena          |
| Tony           | Fernandez     |
| Tony           | Fossas        |
| Tony           | Castillo      |
| Tony           | Perezchica    |
| Tony           | Eusebio       |
| Tony           | Menendez      |
| Tony           | Batista       |
| Tony           | Rodriguez     |
| Tony           | Armas         |
| Tony           | Alvarez       |
| Tony           | Blanco        |
| Tony           | Pena          |
| Tony           | Pena          |
| Tony           | Abreu         |
| Toru           | Murata        |
| Travis         | Blackley      |
| Trent          | Durrington    |
| Trent          | Oeltjen       |
| Trystan        | Magnuson      |
| Tsuyoshi       | Shinjo        |
| Tsuyoshi       | Nishioka      |
| Tsuyoshi       | Wada          |
| Tucupita       | Marcano       |
| Tug            | Thompson      |
| Ty             | LaForest      |
| Tyler          | O'Neill       |
| Tzu-Wei        | Lin           |
| Ubaldo         | Heredia       |
| Ubaldo         | Jimenez       |
| Ugueth         | Urbina        |
| Urbano         | Lugo          |
| Valerio        | De Los Santos |
| Valmy          | Thomas        |
| Vern           | Handrahan     |
| Vic            | Power         |
| Vic            | Davalillo     |
| Vicente        | Amor          |
| Vicente        | Romo          |
| Vicente        | Palacios      |
| Vicente        | Padilla       |
| Vicente        | Campos        |
| Victor         | Cruz          |
| Victor         | Mata          |
| Victor         | Rosario       |
| Victor         | Cole          |
| Victor         | Santos        |
| Victor         | Zambrano      |
| Victor         | Alvarez       |
| Victor         | Martinez      |
| Victor         | Diaz          |
| Victor         | Garate        |
| Victor         | Marte         |
| Victor         | Caratini      |
| Victor         | Alcantara     |
| Victor         | Robles        |
| Victor         | Arano         |
| Victor         | Reyes         |
| Victor         | Gonzalez      |
| Vidal          | Brujan        |
| Vimael         | Machin        |
| Vince          | Shields       |
| Vince          | Barton        |
| Vince          | Gonzales      |
| Vince          | Horsman       |
| Vinny          | Castilla      |
| Vladimir       | Guerrero      |
| Vladimir       | Nunez         |
| Vladimir       | Guerrero      |
| Vladimir       | Gutierrez     |
| Waldis         | Joaquin       |
| Walter         | Carlisle      |
| Walter         | Silva         |
| Wander         | Suero         |
| Wander         | Franco        |
| Wandy          | Rodriguez     |
| Wandy          | Peralta       |
| Warner         | Madrigal      |
| Warwick        | Saupold       |
| Wascar         | Serrano       |
| Webbo          | Clarke        |
| Webster        | Rivas         |
| Wei-Chieh      | Huang         |
| Wei-Chung      | Wang          |
| Wei-Yin        | Chen          |
| Welington      | Castillo      |
| Wenty          | Ford          |
| Wiki           | Gonzalez      |
| Wil            | Culmer        |
| Wil            | Cordero       |
| Wil            | Nieves        |
| Wil            | Ledezma       |
| Wilfredo       | Tejada        |
| Wilfredo       | Rodriguez     |
| Wilfredo       | Tovar         |
| Wilfredo       | Boscan        |
| Wilin          | Rosario       |
| Wilkin         | Ruan          |
| Wilkin         | Castillo      |
| Wilkin         | Ramirez       |
| Wilking        | Rodriguez     |
| Will           | Ohman         |
| Willi          | Castro        |
| William        | Suero         |
| William        | Bergolla      |
| William        | Cuevas        |
| William        | Contreras     |
| Williams       | Perez         |
| Williams       | Jerez         |
| Willians       | Astudillo     |
| Willie         | Montanez      |
| Willie         | Hernandez     |
| Willie         | Canate        |
| Willie         | Martinez      |
| Willie         | Collazo       |
| Willis         | Otanez        |
| Willis         | Roberts       |
| Willson        | Contreras     |
| Willy          | Miranda       |
| Willy          | Taveras       |
| Willy          | Aybar         |
| Willy          | Garcia        |
| Willy          | Adames        |
| Wilmer         | Font          |
| Wilmer         | Flores        |
| Wilmer         | Difo          |
| Wilson         | Alvarez       |
| Wilson         | Heredia       |
| Wilson         | Delgado       |
| Wilson         | Betemit       |
| Wilson         | Valdez        |
| Wilson         | Ramos         |
| Wilton         | Guerrero      |
| Wilton         | Veras         |
| Wilton         | Lopez         |
| Wily           | Peralta       |
| Wily Mo        | Pena          |
| Win            | Kellum        |
| Win            | Remmerswaal   |
| Winston        | Llenas        |
| Winston        | Abreu         |
| Wladimir       | Balentien     |
| Wyman          | Andrus        |
| Xander         | Bogaerts      |
| Xavier         | Cedeno        |
| Yacksel        | Rios          |
| Yadiel         | Rivera        |
| Yadiel         | Hernandez     |
| Yadier         | Molina        |
| Yainer         | Diaz          |
| Yairo          | Munoz         |
| Yamaico        | Navarro       |
| Yamid          | Haad          |
| Yamil          | Benitez       |
| Yan            | Gomes         |
| Yandy          | Diaz          |
| Yangervis      | Solarte       |
| Yasiel         | Puig          |
| Yasmani        | Grandal       |
| Yasmany        | Tomas         |
| Yasuhiko       | Yabuta        |
| Yefri          | Perez         |
| Yefry          | Ramirez       |
| Yennier        | Cano          |
| Yennsy         | Diaz          |
| Yermin         | Mercedes      |
| Yerry          | De Los Santos |
| Yerry          | Rodriguez     |
| Yhency         | Brazoban      |
| Yhonathan      | Barrios       |
| Yimi           | Garcia        |
| Yip            | Owens         |
| Yoan           | Moncada       |
| Yoan           | Lopez         |
| Yoel           | Hernandez     |
| Yoenis         | Cespedes      |
| Yoervis        | Medina        |
| Yohan          | Pino          |
| Yohan          | Flande        |
| Yohan          | Ramirez       |
| Yohander       | Mendez        |
| Yohanny        | Valera        |
| Yohel          | Pozo          |
| Yolmer         | Sanchez       |
| Yonathan       | Daza          |
| Yonder         | Alonso        |
| Yonny          | Chirinos      |
| Yonny          | Hernandez     |
| Yordan         | Alvarez       |
| Yordano        | Ventura       |
| Yorkis         | Perez         |
| Yorman         | Bazardo       |
| Yorman         | Rodriguez     |
| Yorvit         | Torrealba     |
| Yoshi          | Tsutsugo      |
| Yoshihisa      | Hirano        |
| Yoshinori      | Tateyama      |
| Yoslan         | Herrera       |
| Yovani         | Gallardo      |
| Yovanny        | Lara          |
| Yu             | Darvish       |
| Yu             | Chang         |
| Yuli           | Gurriel       |
| Yunel          | Escobar       |
| Yunesky        | Maya          |
| Yuniesky       | Betancourt    |
| Yunior         | Marte         |
| Yurendell      | de Caster     |
| Yusei          | Kikuchi       |
| Yusmeiro       | Petit         |
| Yusniel        | Diaz          |
| Zach           | Pop           |
| Zoilo          | Versalles     |
| Zoilo          | Almonte       |
+----------------+---------------+
